- .pylintrc
- sciencebeam_judge/conftest.py
- sciencebeam_judge/default_xml_mapping_test.py
- sciencebeam_judge/evaluation_pipeline.py
- sciencebeam_judge/evaluation_utils.py
- sciencebeam_judge/jats_xpath_functions.py
- sciencebeam_judge/jats_xpath_functions_test.py
- sciencebeam_judge/tei_xpath_functions.py
- sciencebeam_judge/tei_xpath_functions_test.py
- sciencebeam_judge/xpath_functions.py
- xml-mapping.conf
Part of the OTS evaluation, we needed to add the option to evaluate the full name.
It also required normalising the name more (OTS/cermine result may provide a single string for the name whereas GROBID other DAR JATS output includes individual name fields, e.g. first name, last name)
> evaluate full name

- sciencebeam_judge/evaluation_pipeline.py
should have been removed when we switched to `sciencebeam-utils`.
> removed deprecated process_sciencebeam_gym_dep_args

- Dockerfile.jupyter
The latest version it's showing warnings in the notebook:
```
"/opt/conda/lib/python3.7/site-packages/matplotlib/cbook/__init__.py:2349: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working\n",
"  if isinstance(obj, collections.Iterator):\n",
```
This will pin it to the last tag that doesn't show the warning. Raised #51 to upgrade to the latest version of minimal-notebook (I'm assuming with Python 3.7).
> pinned minimal-notebook version

- Jenkinsfile
This will test that the notebook isn't or doesn't seem to be broken (e.g. `matplotlib` is only used by the notebook).
The scripts will run `docker-compose --rm` - not sure if we need a `docker-compose down -v`.
It will also not use `docker-compose.ci.yml` for those steps.
> run update-example-data-results and -notebooks as part of build

- sciencebeam_judge/default_xml_mapping_test.py
- xml-mapping.conf
The example training data may contain the title multiple times, e.g. when it appears in the heading.
> updated xml mapping to only match first training tei title

- notebooks/conversion-results-details.ipynb
- notebooks/conversion-results-summary.ipynb
The `dataset_suffixes`, however clunky, couldn't practically be passed in as a string (via papermill).
This provides a fix for that.
> fixed dataset_suffixes notebook parsing

- Dockerfile.jupyter
- Makefile
- docker-compose.override.yml
- requirements.notebook.txt
Papermill helps with passing parameters in to notebooks.
While the gcloud sdk will be used to download files from cloud storage (within Kubernetes / GKE the credentials will be magically available).
> added papermill and gcloud sdk to jupyter image for offline notebook rendering

- Jenkinsfile
The [recent build](https://alfred.elifesciences.org/job/libraries/job/library-sciencebeam-judge/90/console) failed when checkout out master due to changes in the notebook. This will revert any local git changes before switching to master.
> revert temporary git changes after updating notebook

- sciencebeam_judge/parsing/xpath/tei_xpath_functions.py
- tests/parsing/xpath/tei_xpath_functions_test.py
after including the label in the raw affiliation, this cause the value to be considered empty and give it a low score
> fixed tei raw affiliation empty if label present

- sciencebeam_judge/evaluation_config.py
- sciencebeam_judge/evaluation_pipeline.py
- sciencebeam_judge/utils/string.py
- tests/conftest.py
- tests/evaluation_pipeline_test.py
- tests/utils/string_test.py
allows the scoring type to be overridden (e.g. to save compute time)
> added --scoring-type-overrides arg

- .pylintrc
- sciencebeam_judge/grobid_evaluate.py
- tests/grobid_evaluate_test.py
avoid grobid evaluation failing when specifying scoring measures not including `exact` (e.g. only `levenshtein`)
> fixed grobid evaluation without exact measure

- Dockerfile
- pytest.ini
to avoid the warning complaining about the unknown marker "slow"
> added missing pytest marker config slow

- Makefile
- sciencebeam_judge/evaluation_pipeline.py
- sciencebeam_judge/evaluation_utils.py
- tests/evaluation_pipeline_test.py
didn't test the usage of `plus_minus_comma_separated_str_to_list` properly, which was missing the `default_value`
> fixed fields argument with plus_minus_comma_separated_str_to_list

- sciencebeam_judge/parsing/xpath/tei_xpath_functions.py
- tests/default_xml_mapping/tei_test.py
- tests/parsing/xpath/tei_xpath_functions_test.py
- xml-mapping.conf
This allows the raw affiliations text with the same label to be joined together for evaluation purpose.
> added affiliation_by_label_text

- Makefile
- sciencebeam_judge/default_field_names.py
- sciencebeam_judge/evaluation/scoring_methods.py
- sciencebeam_judge/evaluation/scoring_types/list.py
- sciencebeam_judge/utils/distance_matching.py
- tests/evaluation_pipeline_test.py
- tests/utils/distance_matching_test.py
#345 introduced an improved distance matching that was making evaluation faster for paragraph evaluation as `partial_ulist`.
Unfortunately it was making it slower for fields like `reference_author_surnames` that are evaluated using tuples of strings rather than strings.
This updates the evaluation to be in line with the previous implementation (supporting tuples rather than converting them to string)
> revise distance matching implementation

- evaluation.conf
- sciencebeam_judge/default_field_names.py
- tests/default_xml_mapping/jats_test.py
- tests/default_xml_mapping/tei_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/91
renaming the fields makes it more clear what is being evaluated
> renamed section_* fields to body_section_*

- requirements.dev.txt
- tests/evaluation_pipeline_test.py
Therefore do not directly depend on `mock` anymore.
This requires `sciencebeam-utils>=0.1.3` (https://github.com/elifesciences/sciencebeam-utils/pull/147)
> switched to using unittest.mock

- README.md
- evaluation.yml
part of https://github.com/elifesciences/sciencebeam-issues/issues/128
This expands on the default deleted text configuration. Configuring the following fields:
- body_section_paragraphs_only_deleted_text (body paragraphs vs body paragraphs only)
- body_section_paragraphs_deleted_text (body paragraphs vs most other text)
- all_section_paragraphs_only_deleted_text (all paragraphs vs all paragraphs only)
- all_section_paragraphs_deleted_text (all paragraphs vs most other text)
> update evaluation configuration

- sciencebeam_judge/evaluation_pipeline.py
related to https://github.com/elifesciences/sciencebeam-issues/issues/135
to make use of the parallel execution using the direct runner, one needs to `--direct_num_workers`. This ads the direct runner arguments.
> added direct runner args

- sciencebeam_judge/evaluation_pipeline.py
related to https://github.com/elifesciences/sciencebeam-issues/issues/135
using `--cloud` to run in Google Dataflow didn't actually work anymore.
This is was due to xpath functions not being registered within the worker.
This also adds a new `evaluation_error` metric counter (where `--skip-errors` is used).
> fixed cloud mode

- sciencebeam_judge/evaluation_pipeline.py
- sciencebeam_judge/parsing/xpath/generic_xpath_functions.py
- tests/default_xml_mapping/tei_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/163
The previous xpath mapping used `text()` to ensure the order when joining the section label with the title.
That however didn't work when the section titles contains formatting (child elements).
Changed `generic-join-children` to split the passed in `xpath` on `||`. That way elements are joined in that order.
> fixed section label titles with formatting
