- .dockerignore
- .gitignore
- notebooks/conversion-results-tools.ipynb
Initial notebook to demonstrate evaluation results on the example dataset.
But it will also be configured to produce results for other datasets / tools.
> added conversion results notebook

- xml-mapping.conf
added xml mapping for the section title and paragraph (not included by default because it takes longer to evaluate)
> added section title and paragraph mapping

- notebooks/conversion-results-details.ipynb
It failed to produce the details report for PMC 1943
> reduce memory usage for details notebook

- Dockerfile
- README.md
- requirements.dev.txt
- requirements.prereq.txt
- requirements.txt
- sciencebeam_judge/evaluation/document_scoring_test.py
- sciencebeam_judge/evaluation/score_aggregation.py
- sciencebeam_judge/evaluation/scoring_types/items.py
- sciencebeam_judge/evaluation/scoring_types/list.py
- sciencebeam_judge/evaluation/scoring_types/table.py
- sciencebeam_judge/evaluation_pipeline.py
- sciencebeam_judge/evaluation_pipeline_test.py
- sciencebeam_judge/parsing/xpath/jats_xpath_functions.py
Part of https://github.com/elifesciences/sciencebeam/issues/65
This now depends on the published modules `sciencebeam-utils` and `sciencebeam-alignment`.
> Use sciencebeam utils and sciencebeam-alignment

- Jenkinsfile
to be consistent with other builds
> use dockerComposeRun function

- .travis.yml
> travis to load docker compose ci config

- Jenkinsfile
to be consistent with other builds
> added merge to master step

- example-data/pmc-sample-1943-cc-by-subset-results/evaluation-results/cermine/grobid-formatted-summary-00000-of-00001.txt
- example-data/pmc-sample-1943-cc-by-subset-results/evaluation-results/grobid-tei/grobid-formatted-summary-00000-of-00001.txt
- sciencebeam_judge/grobid_evaluate.py
- sciencebeam_judge/grobid_evaluate_test.py
> fixed extra space in GROBID report

- .travis.yml
Same as #64 but this time for Travis
> run update-example-data-results and -notebooks as part of Travis build

- notebooks/conversion-results-summary.ipynb
> renamed macro avg to mean

- sciencebeam_judge/default_xml_mapping_test.py
- xml-mapping.conf
Allows evaluation of the _title_ and _abstract_ training data.
> added tei training data mapping for title and abstract

- Dockerfile.jupyter
- Jenkinsfile
- Makefile
- docker-compose.override.yml
- docker-compose.yml
This will start pushing the jupyter image to allow generation of the notebook reports from a container (e.g. as part of the pipeline).
> push jupyter image

- .travis.yml
- Dockerfile.jupyter
- Jenkinsfile
- Makefile
- docker-compose.yml
part of https://github.com/elifesciences/issues/issues/5299
> remove python2 from project

- README.md
> updated readme to refer to Python 3 and use makefile

- sciencebeam_judge/parsing/xpath/jats_xpath_functions.py
- tests/default_xml_mapping_test.py
- tests/parsing/xpath/jats_xpath_functions_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/issues/issues/6134
> get doi from jats url link

- tests/default_xml_mapping/jats_test.py
- tests/default_xml_mapping/tei_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/74
> evaluate figure and table independent of section

- .dockerignore
- README.md
fyi @de-code , I'm just going to merge this one without your approval. The travis file has already been removed, this is just linting really.
> travis, removes all mentions

- evaluation.conf
- sciencebeam_judge/default_field_names.py
- tests/default_xml_mapping/jats_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/89
> added all section titles and paragraphs

- Makefile
- evaluation.conf
- requirements.dev.txt
- sciencebeam_judge/evaluation/scoring_methods.py
- sciencebeam_judge/evaluation/scoring_types/list.py
- sciencebeam_judge/utils/distance_matching.py
- tests/utils/distance_matching_perf.py
- tests/utils/distance_matching_profile.py
- tests/utils/distance_matching_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/90
> improved paragraph evaluation speed

- tests/default_xml_mapping/jats_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/91
> include section label in section title

- tests/default_xml_mapping/jats_test.py
- tests/default_xml_mapping/tei_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/91
extension of #358
> section title with label tei

- evaluation.conf
- sciencebeam_judge/default_field_names.py
- tests/default_xml_mapping/jats_test.py
- tests/default_xml_mapping/tei_test.py
- xml-mapping.conf
part of https://github.com/elifesciences/sciencebeam-issues/issues/91
using separate fields, allows the evaluation to be done both ways.
> added separate section labels and label_titles

- Dockerfile.jupyter
- requirements.notebook.txt
part of https://github.com/elifesciences/sciencebeam-issues/issues/98
> upgrade jupyter base image to 016833b15ceb

- Makefile
- README.md
- evaluate.sh
The indirection via `evaluate.sh` doesn't seem to add anything..
> removed evaluate.sh

- README.md
- sciencebeam_judge/extract_fields.py
the extract fields tool helps to see what sciencebeam judge will actually use, based on the xml mapping.
> added extract fields tool

- sciencebeam_judge/evaluation_pipeline.py
related to https://github.com/elifesciences/sciencebeam-issues/issues/135
this allows configuration of additional Dataflow worker options. e.g. the machine type.
> added worker options

- Makefile
- project_tests.sh
- requirements.dev.txt
- requirements.txt
- sciencebeam_judge/evaluation/custom/bounding_box_intersection.py
- sciencebeam_judge/evaluation/custom/deleted_text.py
- sciencebeam_judge/evaluation/document_scoring.py
- sciencebeam_judge/evaluation/match_scoring.py
- sciencebeam_judge/evaluation/normalization.py
- sciencebeam_judge/evaluation/score_aggregation.py
- sciencebeam_judge/evaluation/scoring_methods/scoring_methods.py
- sciencebeam_judge/evaluation/scoring_types/list.py
- sciencebeam_judge/evaluation_config.py
- sciencebeam_judge/evaluation_pipeline.py
- sciencebeam_judge/grobid_evaluate.py
- sciencebeam_judge/parsing/xml.py
- sciencebeam_judge/parsing/xpath/jats_xpath_functions.py
- sciencebeam_judge/utils/config.py
- sciencebeam_judge/utils/distance_matching.py
- sciencebeam_judge/utils/fuzzy.py
- sciencebeam_judge/utils/typing.py
- sciencebeam_judge/utils/xml.py
- tests/utils/distance_matching_profile.py
- tests/utils/distance_matching_test.py
part of https://github.com/elifesciences/sciencebeam-issues/issues/150
added mypy linting (with some workarounds for now).
> added mypy linting

- README.md
part of https://github.com/elifesciences/sciencebeam-issues/issues/237
> updated readme to mention change of stewardship
